import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ApiService } from '../../services/api.service';

@Component({
    selector: 'app-report',
    standalone: true,
    imports: [CommonModule, RouterLink],
    template: `
    <div class="tf-page">
      <nav class="tf-sidebar">
        <div class="tf-sidebar-logo"><div class="logo-text">⚡ TALENTFORGE</div></div>
        <div class="tf-sidebar-content">
          <a class="tf-nav-item" routerLink="/dashboard"><span class="nav-icon">🏠</span> Dashboard</a>
          <a class="tf-nav-item" routerLink="/jd-upload"><span class="nav-icon">📄</span> JD Analysis</a>
          <a class="tf-nav-item" routerLink="/learning"><span class="nav-icon">🧠</span> ForgeAI Learning</a>
          <a class="tf-nav-item" routerLink="/mcq-test"><span class="nav-icon">📝</span> MCQ Test</a>
          <a class="tf-nav-item" routerLink="/weak-areas"><span class="nav-icon">⚠️</span> Weak Areas</a>
          <a class="tf-nav-item" routerLink="/readiness"><span class="nav-icon">🏆</span> Readiness</a>
          <a class="tf-nav-item" routerLink="/career-insights"><span class="nav-icon">💼</span> Career</a>
          <a class="tf-nav-item active" routerLink="/report"><span class="nav-icon">📊</span> Report</a>
        </div>
      </nav>

      <main class="tf-main with-sidebar">
        <div class="tf-page-header">
          <h1 class="tf-page-title">📊 Performance Report</h1>
          <p class="tf-page-subtitle">Download your complete interview readiness report generated by ForgeAI</p>
        </div>

        <div class="report-center">
          <div class="report-preview tf-card">
            <div class="rp-header">
              <div class="rp-logo">⚡ TALENTFORGE</div>
              <div class="rp-sub">AI Interview Readiness Report</div>
              <div class="rp-sub2">Powered by ForgeAI</div>
            </div>
            <div class="rp-divider"></div>
            <div class="rp-sections">
              <div class="rp-section">
                <div class="rps-icon">👤</div>
                <div class="rps-title">Candidate Profile</div>
                <div class="rps-desc">Name, email, role, skills, and generation timestamp</div>
              </div>
              <div class="rp-section">
                <div class="rps-icon">🏆</div>
                <div class="rps-title">Final Readiness Score</div>
                <div class="rps-desc">Weighted formula result with level classification</div>
              </div>
              <div class="rp-section">
                <div class="rps-icon">📊</div>
                <div class="rps-title">Score Breakdown Table</div>
                <div class="rps-desc">MCQ, Coding, JD Match, Learning scores with weights</div>
              </div>
              <div class="rp-section">
                <div class="rps-icon">📐</div>
                <div class="rps-title">Scoring Formula</div>
                <div class="rps-desc">(MCQ×35%) + (Coding×30%) + (JD Match×20%) + (Learning×15%)</div>
              </div>
            </div>
            <div class="rp-divider"></div>
            <div class="rp-footer">
              TalentForge AI — Confidential Interview Readiness Report
            </div>
          </div>

          <div class="report-actions">
            <div *ngIf="success" class="tf-alert tf-alert-success">✅ {{ success }}</div>
            <div *ngIf="error" class="tf-alert tf-alert-error">⚠️ {{ error }}</div>
            <button class="tf-btn tf-btn-primary tf-btn-lg" (click)="download()" [disabled]="loading">
              <span *ngIf="loading" class="spinner"></span>
              {{ loading ? 'Generating PDF...' : '📄 Download PDF Report' }}
            </button>
            <p class="dl-hint">
              Your report will be downloaded as <strong>TalentForge_Readiness_Report.pdf</strong>
            </p>
            <div class="dl-note">
              <span>💡</span>
              Complete the Readiness Score page first to include score data in your report.
            </div>
          </div>
        </div>
      </main>
    </div>
  `,
    styles: [`
    .report-center { display:flex; flex-direction:column; align-items:center; gap:32px; max-width:600px; margin:0 auto; }
    .report-preview { width:100%; padding:32px; }
    .rp-header { text-align:center; margin-bottom:20px; }
    .rp-logo { font-size:22px; font-weight:900; letter-spacing:3px; background:var(--tf-grad-brand); -webkit-background-clip:text; -webkit-text-fill-color:transparent; background-clip:text; margin-bottom:6px; }
    .rp-sub { font-size:14px; color:var(--tf-text-secondary); margin-bottom:2px; }
    .rp-sub2 { font-size:11px; color:var(--tf-text-muted); }
    .rp-divider { height:1px; background:var(--tf-border); margin:20px 0; }
    .rp-sections { display:flex; flex-direction:column; gap:12px; }
    .rp-section { display:flex; gap:14px; align-items:flex-start; padding:12px; background:var(--tf-card); border-radius:var(--tf-radius-sm); }
    .rps-icon { font-size:22px; flex-shrink:0; }
    .rps-title { font-size:14px; font-weight:700; margin-bottom:2px; }
    .rps-desc { font-size:12px; color:var(--tf-text-secondary); }
    .rp-footer { text-align:center; font-size:11px; color:var(--tf-text-muted); }
    .report-actions { width:100%; text-align:center; }
    .dl-hint { font-size:13px; color:var(--tf-text-secondary); margin-top:12px; }
    .dl-note { display:flex; gap:8px; align-items:flex-start; background:rgba(0,212,255,0.06); border:1px solid var(--tf-border-glow); border-radius:var(--tf-radius-sm); padding:12px 16px; font-size:13px; color:var(--tf-text-secondary); text-align:left; margin-top:16px; }
  `]
})
export class ReportComponent {
    loading = false;
    error = '';
    success = '';

    constructor(private apiService: ApiService) { }

    download(): void {
        this.loading = true; this.error = ''; this.success = '';
        this.apiService.downloadReport().subscribe({
            next: (blob) => {
                const url = window.URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = 'TalentForge_Readiness_Report.pdf';
                a.click();
                window.URL.revokeObjectURL(url);
                this.success = 'Report downloaded successfully!';
                this.loading = false;
            },
            error: () => { this.error = 'Failed to generate report. Please try again.'; this.loading = false; }
        });
    }
}
